"""Add exercise ordering and set timestamps

Revision ID: 07bc662ed145
Revises: 17c8e4ab9073
Create Date: 2026-06-17 15:34:07.788367

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '07bc662ed145'
down_revision = '17c8e4ab9073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("CURRENT_TIMESTAMP"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
