"""Remove set_number from workout_set

Revision ID: 17c8e4ab9073
Revises: bdf67addee30
Create Date: 2026-06-15 12:10:15.398353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c8e4ab9073'
down_revision = 'bdf67addee30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_column('set_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_number', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
